-- 监管企业监管员菜单权限
INSERT INTO `syjzhpt`.`sysfunction` (`FUNCTIONID`, `LOCATION`, `TITLE`, `PARENT`, `ORDERNO`, `TYPE`, `DESCRIPTION`, `LOG`, `OWNER`, `ACTIVE`, `FUNCTIONCODE`, `VISIBLE`, `BIZID`, `ROLBIZCLASS`, `IMAGEURL`, `EXPANDEDIMAGEURL`, `AAA102`, `CAE005`, `ROLBIZABLE`, `TARGET`, `SYSTEMCODE`) 
VALUES ('2016121209391080119288189', '/jk/jkgl/jkqyjgyIndex', '监管企业监管员', '8009', '1', '1', NULL, NULL, NULL, NULL, NULL, '1', 'jkqyjgyIndex', NULL, NULL, NULL, NULL, NULL, NULL, '', 'spjkxt');

-- 监管企业指派监管员按钮权限
INSERT INTO `syjzhpt`.`sysfunction` (`FUNCTIONID`, `LOCATION`, `TITLE`, `PARENT`, `ORDERNO`, `TYPE`, `DESCRIPTION`, `LOG`, `OWNER`, `ACTIVE`, `FUNCTIONCODE`, `VISIBLE`, `BIZID`, `ROLBIZCLASS`, `IMAGEURL`, `EXPANDEDIMAGEURL`, `AAA102`, `CAE005`, `ROLBIZABLE`, `TARGET`, `SYSTEMCODE`) 
VALUES ('2016121217114002325469292', '/jk/jkgl/addFzrJgy', '指派监管员', '2016121209391080119288189', '1', '2', NULL, NULL, NULL, NULL, NULL, '1', 'addFzrJgy', NULL, NULL, NULL, NULL, NULL, NULL, '', 'spjkxt');
