-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.315.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2016/9/1 18:53:07
-- Server version: 5.6.26-log
-- Client version: 4.1

SET NAMES 'utf8';

CREATE TABLE syjzhpt.zfwsxwdctzs (
  xwdctzsid VARCHAR(32) NOT NULL COMMENT '询问调查通知书id',
  ajdjid VARCHAR(32) DEFAULT NULL COMMENT '案件登记id',
  xwdcsbh VARCHAR(50) DEFAULT NULL COMMENT '询问调查通知书编号',
  xwdcdsr VARCHAR(200) DEFAULT NULL COMMENT '询问调查通知书当事人',
  xwdczynr VARCHAR(255) DEFAULT NULL COMMENT '询问调查通知书主要内容',
  xwdcjzrq DATETIME DEFAULT NULL COMMENT '询问调查通知书截止日期',
  xwdcxwdz VARCHAR(255) DEFAULT NULL COMMENT '询问调查通知书询问地址',
  xwdcxdzl VARCHAR(255) DEFAULT NULL COMMENT '询问调查通知书携带资料',
  xwdcqzrq DATETIME DEFAULT NULL COMMENT '询问调查通知书签字日期',
  xwdcdsrqz VARCHAR(30) DEFAULT NULL COMMENT '询问调查通知书当事人签字',
  xwdcdsrqzrq DATETIME DEFAULT NULL COMMENT '询问调查通知书当事人签字日期',
  PRIMARY KEY (xwdctzsid)
)
ENGINE = INNODB
COMMENT = '询问调查通知书';
 
INSERT INTO syjzhpt.pfjcs(FJCSID, FJCSDMLB, FJCSDMLBMC, FJCSDMZ, FJCSDMMC, FJCSKSRQ, FJCSZZRQ, FJCSQYFLAG, FJCSFJBC, ZFWSURL, FJCSZFWSTITLE, fjcsdlbh, fjcsdlmc, fjcssfdx, zfwstabname, zfwstabid) VALUES
('89', 'ZFAJZFWS', '执法案件文书', 'ZFAJZFWS44', '44询问调查通知书', '199405', NULL, '1', '1', '/pub/wsgldy/zfwsxwdctzsIndex', NULL, NULL, NULL, NULL, NULL, NULL);


