-- 课件管理菜单
INSERT INTO syjzhpt.sysfunction(FUNCTIONID, LOCATION, TITLE, PARENT, ORDERNO, TYPE, DESCRIPTION, LOG, OWNER, ACTIVE, FUNCTIONCODE, VISIBLE, BIZID, ROLBIZCLASS, IMAGEURL, EXPANDEDIMAGEURL, AAA102, CAE005, ROLBIZABLE, TARGET, SYSTEMCODE) VALUES
('2017041110373667632388996', '/train/courseware/coursewareManagerIndex', '课件管理', '2017041015310304348359860', 1, '1', NULL, NULL, NULL, NULL, NULL, '1', 'coursewareManagerIndex', NULL, NULL, NULL, NULL, NULL, NULL, '', '');
-- 添加课件
INSERT INTO syjzhpt.sysfunction(FUNCTIONID, LOCATION, TITLE, PARENT, ORDERNO, TYPE, DESCRIPTION, LOG, OWNER, ACTIVE, FUNCTIONCODE, VISIBLE, BIZID, ROLBIZCLASS, IMAGEURL, EXPANDEDIMAGEURL, AAA102, CAE005, ROLBIZABLE, TARGET, SYSTEMCODE) VALUES
('2017041110382772563182026', '/train/courseware/coursewareInfoFormIndex', '添加课件', '2017041214400306918282520', 1, '2', NULL, NULL, NULL, NULL, NULL, '1', 'coursewareInfoFormIndex', NULL, NULL, NULL, NULL, NULL, NULL, '', '');
-- 修改课件 
INSERT INTO syjzhpt.sysfunction(FUNCTIONID, LOCATION, TITLE, PARENT, ORDERNO, TYPE, DESCRIPTION, LOG, OWNER, ACTIVE, FUNCTIONCODE, VISIBLE, BIZID, ROLBIZCLASS, IMAGEURL, EXPANDEDIMAGEURL, AAA102, CAE005, ROLBIZABLE, TARGET, SYSTEMCODE) VALUES
('2017041210310998174983047', '/train/courseware/editCoursewareInfo', '修改课件', '2017041214400306918282520', 1, '2', NULL, NULL, NULL, NULL, NULL, '1', 'editCoursewareInfo', NULL, NULL, NULL, NULL, NULL, NULL, '', '');
-- 删除教师
INSERT INTO syjzhpt.sysfunction(FUNCTIONID, LOCATION, TITLE, PARENT, ORDERNO, TYPE, DESCRIPTION, LOG, OWNER, ACTIVE, FUNCTIONCODE, VISIBLE, BIZID, ROLBIZCLASS, IMAGEURL, EXPANDEDIMAGEURL, AAA102, CAE005, ROLBIZABLE, TARGET, SYSTEMCODE) VALUES
('2017041210334108671754342', '/train/courseware/delCoursewareInfos', '删除课件', '2017041214400306918282520', 1, '2', NULL, NULL, NULL, NULL, NULL, '1', 'delCoursewareInfos', NULL, NULL, NULL, NULL, NULL, NULL, '', '');
-- 查看课件
INSERT INTO syjzhpt.sysfunction(FUNCTIONID, LOCATION, TITLE, PARENT, ORDERNO, TYPE, DESCRIPTION, LOG, OWNER, ACTIVE, FUNCTIONCODE, VISIBLE, BIZID, ROLBIZCLASS, IMAGEURL, EXPANDEDIMAGEURL, AAA102, CAE005, ROLBIZABLE, TARGET, SYSTEMCODE) VALUES
('2017042114323410425510280', '/train/courseware/showCourseWare', '查看 课件', '2017041214400306918282520', 1, '2', NULL, NULL, NULL, NULL, NULL, '1', 'showCourseWare', NULL, NULL, NULL, NULL, NULL, NULL, '', '');

-- 课件信息表
CREATE TABLE syjzhpt.ots_courseware (
ware_id varchar(32) NOT NULL COMMENT '课件ID',
ware_name varchar(20) DEFAULT NULL COMMENT '课件名称',
ware_status varchar(32) DEFAULT NULL COMMENT '课件状态 ',
ware_credit int(10) DEFAULT NULL COMMENT '所需积分  ',
ware_category varchar(32) DEFAULT NULL COMMENT '课件分类ID  ',
ware_type varchar(32) DEFAULT NULL COMMENT '课件类型  ',
ware_source varchar(32) DEFAULT NULL COMMENT '课件来源ID  ',
ware_video mediumtext DEFAULT NULL COMMENT '课件路径  ',
ware_des mediumtext DEFAULT NULL COMMENT '课件讲义源码 ',
ware_length float DEFAULT NULL COMMENT '媒体时长 ',
ware_des_h mediumtext DEFAULT NULL COMMENT '课件讲义源码 ',
ware_point decimal  DEFAULT NULL COMMENT '课件学分 ',
aae011 varchar(32) DEFAULT NULL COMMENT '经办人 ',  
aae036 datetime  DEFAULT NULL COMMENT '经办时间 ',  
PRIMARY KEY (ware_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '课件信息表';


-- 下拉框参数维护（课件来源）
call PRC_INSERTCODE('KJLY','课件来源','1','1','网络下载','199405',null,@P_CODE,@P_MSG); 
call PRC_INSERTCODE('KJLY','课件来源','1','2','市场购买','199405',null,@P_CODE,@P_MSG);
call PRC_INSERTCODE('KJLY','课件来源','1','3','自主开发','199405',null,@P_CODE,@P_MSG);

-- 下拉框参数维护（课件分类）
call PRC_INSERTCODE('KJFL','课件分类','1','1','演示课件','199405',null,@P_CODE,@P_MSG); 

-- 下拉框参数维护（课件类型）
call PRC_INSERTCODE('KJLX','课件类型','1','1','视频','199405',null,@P_CODE,@P_MSG); 
call PRC_INSERTCODE('KJLX','课件类型','1','2','图片','199405',null,@P_CODE,@P_MSG);
call PRC_INSERTCODE('KJLX','课件类型','1','3','PDF','199405',null,@P_CODE,@P_MSG);

