-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.315.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2016/12/8 11:31:59
-- Server version: 5.5.28
-- Client version: 4.1

SET NAMES 'utf8';
INSERT INTO syjzhpt.aa01(AAA001, AAA002, AAA005, AAA104, AAA105, AAZ499, AAA027) VALUES
('isDebug', '是否开始调试模式', 'true', '1', '', '2016120811054344771653827', '4');
