-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.315.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2016/8/29 11:13:16
-- Server version: 5.5.27
-- Client version: 4.1

SET NAMES 'utf8';

USE syjzhpt;


--
-- Alter table "zfwszlgztzs20"
--
ALTER TABLE zfwszlgztzs20
  ADD COLUMN zlgzdsrqz VARCHAR(30) DEFAULT NULL COMMENT '当事人签字' AFTER zlgzdsr,
  ADD COLUMN zlgzdsrqzrq DATETIME DEFAULT NULL COMMENT '当事人签字日期' AFTER zlgzdsrqz;

--
-- Alter table "zfwsajjttljl19"
--
ALTER TABLE zfwsajjttljl19
  ADD COLUMN jttljssj DATETIME DEFAULT NULL COMMENT '集体讨论结束时间' AFTER jttldsr,
  ADD COLUMN jttlzcrzw VARCHAR(50) DEFAULT NULL COMMENT '主持人职务' AFTER jttljssj,
  ADD COLUMN jttljlrzw VARCHAR(50) DEFAULT NULL COMMENT '记录人职务' AFTER jttlzcrzw;


--
-- Alter table "zfwsjccfkyjds17"
--
ALTER TABLE zfwsjccfkyjds17
  ADD COLUMN jckydsrqz VARCHAR(30) DEFAULT NULL COMMENT '当事人签字' AFTER jckyfj,
  ADD COLUMN jckydsrqzrq DATETIME DEFAULT NULL COMMENT '当事人签字日期' AFTER jckydsrqz;



--
-- Alter table "zfwsxxclwptzs16"
--
ALTER TABLE zfwsxxclwptzs16
  ADD COLUMN xxcldsrqz VARCHAR(30) DEFAULT NULL COMMENT '当事人签字' AFTER xxclfj,
  ADD COLUMN xxcldsrqzrq DATETIME DEFAULT NULL COMMENT '当事人签字日期' AFTER xxcldsrqz;




--
-- Alter table "zfwscfkyyqtzs15"
--
ALTER TABLE zfwscfkyyqtzs15
  ADD COLUMN cfyqdsrqz VARCHAR(30) DEFAULT NULL COMMENT '当事人签字' AFTER cfyqrmfy,
  ADD COLUMN cfyqdsrqzrq DATETIME DEFAULT NULL COMMENT '当事人签字日期' AFTER cfyqdsrqz;



--
-- Alter table "zfwsjyjcjyjdgzs14"
--
ALTER TABLE zfwsjyjcjyjdgzs14
  ADD COLUMN jygzdsrqz VARCHAR(30) DEFAULT NULL COMMENT '当事人签字' AFTER jygzdsr,
  ADD COLUMN jygzdsrqzrq DATETIME DEFAULT NULL COMMENT '当事人签字日期' AFTER jygzdsrqz;


--
-- Alter table "zfwsxxdjbcwpcljds11"
--
ALTER TABLE zfwsxxdjbcwpcljds11
  ADD COLUMN xxcldsrqz VARCHAR(30) DEFAULT NULL COMMENT '当事人签字' AFTER xxclfjxx,
  ADD COLUMN xxcldsrqzrq DATETIME DEFAULT NULL COMMENT '当事人签字日期' AFTER xxcldsrqz,
  ADD COLUMN xxclzfry1 VARCHAR(30) DEFAULT NULL COMMENT '执法人员1' AFTER xxcldsrqzrq,
  ADD COLUMN xxclzfry2 VARCHAR(30) DEFAULT NULL COMMENT '执法人员2' AFTER xxclzfry1,
  ADD COLUMN xxclzfzh1 VARCHAR(30) DEFAULT NULL COMMENT '执法证号1' AFTER xxclzfry2,
  ADD COLUMN xxclzfzh2 VARCHAR(30) DEFAULT NULL COMMENT '执法证号2' AFTER xxclzfzh1,
  ADD COLUMN xxclzfryqzrq DATETIME DEFAULT NULL COMMENT '执法人员签字日期' AFTER xxclzfzh2;




--
-- Alter table "zfwsxxdjbcwptzs10"
--
ALTER TABLE zfwsxxdjbcwptzs10
  ADD COLUMN xztzdsrqz VARCHAR(30) DEFAULT NULL COMMENT '当事人签字' AFTER xztzfjxx,
  ADD COLUMN xztzdsrqzrq DATETIME DEFAULT NULL COMMENT '当事人签字日期' AFTER xztzdsrqz,
  ADD COLUMN xztzzfryqz1 VARCHAR(30) DEFAULT NULL COMMENT '执法人员签字1' AFTER xztzdsrqzrq,
  ADD COLUMN xztzzfryqz2 VARCHAR(30) DEFAULT NULL COMMENT '执法人员签字2' AFTER xztzzfryqz1,
  ADD COLUMN xztzzfryqzrq DATETIME DEFAULT NULL COMMENT '执法人员签字日期' AFTER xztzzfryqz2,
  ADD COLUMN xztzzfzh1 VARCHAR(20) DEFAULT NULL COMMENT '执法证号1' AFTER xztzzfryqzrq,
  ADD COLUMN xztzzfzh2 VARCHAR(20) DEFAULT NULL COMMENT '执法证号2' AFTER xztzzfzh1,
  ADD COLUMN xztzbcqxksrq DATETIME DEFAULT NULL COMMENT '保存期限开始日期' AFTER xztzzfzh2,
  ADD COLUMN xztzbcqxjsrq DATETIME DEFAULT NULL COMMENT '保存期限结束日期' AFTER xztzbcqxksrq;




--
-- Alter table "zfwsxcjcbl8"
--
ALTER TABLE zfwsxcjcbl8
  ADD COLUMN xcjcjlrqz VARCHAR(30) DEFAULT NULL COMMENT '记录人签字' AFTER xcjczfryqz2,
  ADD COLUMN xcjcjlrqzrq DATETIME DEFAULT NULL COMMENT '记录人签字日期' AFTER xcjcjlrqz,
    ADD COLUMN ajdjay VARCHAR(255) DEFAULT NULL COMMENT '案由' AFTER xcjczfry,
  ADD COLUMN commc VARCHAR(30) DEFAULT NULL COMMENT '被检查单位(人)' AFTER ajdjay,
  ADD COLUMN comdz VARCHAR(255) DEFAULT NULL COMMENT '企业地址' AFTER commc,
  ADD COLUMN comfrhyz VARCHAR(50) DEFAULT NULL COMMENT '企业法人/业主' AFTER comdz,
  ADD COLUMN comyddh VARCHAR(20) DEFAULT NULL COMMENT '电话' AFTER comfrhyz;
  
  
--
-- Alter table "zfwsxwdcbl7"
--
ALTER TABLE zfwsxwdcbl7
  ADD COLUMN dcblbdcrzwhzy VARCHAR(50) DEFAULT NULL COMMENT '被调查人职务或职业' AFTER dcbljlrqzrq,
  ADD COLUMN dcblbdcryb VARCHAR(10) DEFAULT NULL COMMENT '被调查人邮编' AFTER dcblbdcrzwhzy;




--
-- Alter table "zfwssxfzajyss5"
--
ALTER TABLE zfwssxfzajyss5
  ADD COLUMN lxr VARCHAR(30) DEFAULT NULL COMMENT '联系人' AFTER dsr,
  ADD COLUMN lxdh VARCHAR(20) DEFAULT NULL COMMENT '联系电话' AFTER lxr;

  

--
-- Alter table "zfwssxfzajysspb4"
--
ALTER TABLE zfwssxfzajysspb4
  ADD COLUMN fgfzryj VARCHAR(1000) DEFAULT NULL COMMENT '分管负责人意见' AFTER ajdjajly,
  ADD COLUMN fgfzrqz VARCHAR(30) DEFAULT NULL COMMENT '分管负责人签字' AFTER fgfzryj,
  ADD COLUMN fgfzrqzrq DATETIME DEFAULT NULL COMMENT '分管负责人签字日期' AFTER fgfzrqz;














