ALTER TABLE fj
  ADD COLUMN FJCSDMZ VARCHAR(20) DEFAULT NULL COMMENT '对应PFJCS表字段' AFTER FJNAME,
  ADD COLUMN fjuserid VARCHAR(32) DEFAULT NULL COMMENT '附件userid' AFTER FJCSDMZ,
  ADD COLUMN fjczyxm VARCHAR(30) DEFAULT NULL COMMENT '操作员姓名' AFTER fjuserid,
  ADD COLUMN fjczsj DATETIME DEFAULT NULL COMMENT '操作时间' AFTER fjczyxm;
