
INSERT INTO syjzhpt.sysfunction(FUNCTIONID, LOCATION, TITLE, PARENT, ORDERNO, TYPE, DESCRIPTION, LOG, OWNER, ACTIVE, FUNCTIONCODE, VISIBLE, BIZID, ROLBIZCLASS, IMAGEURL, EXPANDEDIMAGEURL, AAA102, CAE005, ROLBIZABLE, TARGET, SYSTEMCODE) VALUES
('2016072214071768654950925', '/pcompany/upLoadApproveComExcel', '审批企业模板上传', '1129', 1, '2', NULL, NULL, NULL, NULL, NULL, '1', 'upLoadApproveComExcel', NULL, NULL, NULL, NULL, NULL, NULL, '', '');

INSERT INTO syjzhpt.sysfunction(FUNCTIONID, LOCATION, TITLE, PARENT, ORDERNO, TYPE, DESCRIPTION, LOG, OWNER, ACTIVE, FUNCTIONCODE, VISIBLE, BIZID, ROLBIZCLASS, IMAGEURL, EXPANDEDIMAGEURL, AAA102, CAE005, ROLBIZABLE, TARGET, SYSTEMCODE) VALUES
('2017090816010607582027852', '/pcompany/importApproveCom', '审批企业导入', '1129', 1, '2', NULL, NULL, NULL, NULL, NULL, '1', 'importApproveCom', NULL, NULL, NULL, NULL, NULL, NULL, '', '');

INSERT INTO syjzhpt.sysfunction(FUNCTIONID, LOCATION, TITLE, PARENT, ORDERNO, TYPE, DESCRIPTION, LOG, OWNER, ACTIVE, FUNCTIONCODE, VISIBLE, BIZID, ROLBIZCLASS, IMAGEURL, EXPANDEDIMAGEURL, AAA102, CAE005, ROLBIZABLE, TARGET, SYSTEMCODE) VALUES
('2017091111461898629249292', '/pcompany/saveApprovePcompanydr', '保存审批企业导入', '1129', 1, '2', NULL, NULL, NULL, NULL, NULL, '1', 'saveApprovePcompanydr', NULL, NULL, NULL, NULL, NULL, NULL, '', '');

INSERT INTO syjzhpt.sysfunction(FUNCTIONID, LOCATION, TITLE, PARENT, ORDERNO, TYPE, DESCRIPTION, LOG, OWNER, ACTIVE, FUNCTIONCODE, VISIBLE, BIZID, ROLBIZCLASS, IMAGEURL, EXPANDEDIMAGEURL, AAA102, CAE005, ROLBIZABLE, TARGET, SYSTEMCODE) VALUES
('2017091111482891365097889', '/pcompany/exportApproveToExcel', '审批企业信息导出', '1129', 1, '2', NULL, NULL, NULL, NULL, NULL, '1', 'exportApproveToExcel', NULL, NULL, NULL, NULL, NULL, NULL, '', '');
