-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.315.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2017/11/23 16:44:09
-- Server version: 5.0.96-community-nt
-- Client version: 4.1

-- 用户表添加字段（用于用户注册）
SET NAMES 'utf8';


ALTER TABLE sysuser
  ADD COLUMN userdwmc VARCHAR(100) DEFAULT NULL COMMENT '用户单位名称' AFTER userjc,
  ADD COLUMN userlxdz VARCHAR(255) DEFAULT NULL COMMENT '用户联系地址ַ' AFTER userdwmc,
  ADD COLUMN useremail VARCHAR(50) DEFAULT NULL COMMENT '用户电子邮箱' AFTER userlxdz,
  ADD COLUMN findpwsn VARCHAR(255) DEFAULT NULL COMMENT '找回密码时生成的随机数' AFTER useremail;
